/*
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */

package main

import (
	"fmt"
)

func fib_even_sum(max int) (sum int) {

	sum = 0
	a, b := 1, 0

	for b < max {
		a, b = b, a+b
		if (b)%2 == 0 {
			sum += b
		}

	}
	return
}

func main() {
	sum := fib_even_sum(4000000)
	fmt.Println(sum)
	// 4613732 is the correct answer
}
